### ISSUE TITLE
Error in running ssmult_install.m

### ISSUE THREAD

**Issue by jimingjlu** [PetterS/SuiteSparse#4]

**Comment by PetterS** [comment]
Please contact the original author.

**Comment by jimingjlu** [comment]
My matlab is R2014a, the system is Win7.
cmd = sprintf ('mex -O%s ssmult.c ssmult_mex.c ssmult_saxpy.c ssmult_dot.c ssmult_transpose.c', d) ;
eval(cmd);
The error is 
'Error using mex
ssmult_saxpy.c'
What is the problem? I'm waiting for your answer. Thank you very much.
